-- Creating new workgroups
insert into `shelters`.`core_admin_workgroup` (`workgroup_key`, `workgroup_description`) VALUES ('ProjectPLASE', 'Project PLASE restricted workgroup');
insert into `shelters`.`core_admin_workgroup` (`workgroup_key`, `workgroup_description`) VALUES ('FellowshipOfLights', 'Fellowship of Lights restricted workgroup');
insert into `shelters`.`core_admin_workgroup` (`workgroup_key`, `workgroup_description`) VALUES ('SalvationArmyBoothHouseShelter', 'Salvation Army - Booth House Shelter restricted workgroup');
insert into `shelters`.`core_admin_workgroup` (`workgroup_key`, `workgroup_description`) VALUES ('PrisonersAidAssociationOfMaryland', 'Prisoners Aid Association of Maryland restricted workgroup');
insert into `shelters`.`core_admin_workgroup` (`workgroup_key`, `workgroup_description`) VALUES ('MannaHouse', 'Manna House restricted workgroup');

-- Creating a new user 
INSERT INTO `shelters`.`core_admin_user` (`id_user`, `access_code`, `last_name`, `first_name`, `email`, `status`, `password`, `locale`, `level_user`, `reset_password`, `accessibility_mode`, `password_max_valid_date`, `account_max_valid_date`, `nb_alerts_sent`, `last_login`, `workgroup_key`) VALUES (5, 'john', 'Doe', 'John', 'johndoe@johndoe.com', 1, 'PLAINTEXT:johnjohn', 'en', 0, 0, 0, '2019-01-01 00:00:00', '1568573366125', 0, '1980-01-01 00:00:00', 'all');

-- assigning the newly created user to a new workgroup we just created
insert into `shelters`.`core_admin_workgroup_user` (`workgroup_key`, `id_user`) VALUES ('ProjectPLASE', 5);

-- creating all shelters for the example and linking them to their respective workgroups
INSERT INTO `shelters`.`shelters_shelter` (`id_shelter`, `name`, `description`, `email`, `web_site`, `workgroup_key`, `reminder_status`, `bed_capacity`, `phone_number`, `address`, `location_lat`, `location_lon`) VALUES ('1', 'Project PLASE', 'Project PLASE, Inc. addresses homelessness in Baltimore by providing transitional housing, permanent housing and supportive services to homeless adults. We serve the most vulnerable and underserved, including persons with mental illness, HIV/AIDS, addiction, developmental disabilities, and ex-offend', 'jacob.green@gmail.com', 'http://projectplase.org/', 'ProjectPLASE', '1', '10', '410-837-1400', '1814 Maryland Avenue, Baltimore, MD 21201', '39.310451', '-76.618055');
INSERT INTO `shelters`.`shelters_shelter` (`id_shelter`, `name`, `description`, `email`, `web_site`, `workgroup_key`, `reminder_status`, `bed_capacity`, `phone_number`, `address`, `location_lat`, `location_lon`) VALUES ('2', 'Fellowship of Lights', 'shelter for children only, 12-17 years old', 'jacob.green@gmail.com', '', 'FellowshipOfLights', '1', '10', '410-332-4277', '1101 St Paul St # 111, Baltimore, MD 21202', '39.303015', '-76.614043');
INSERT INTO `shelters`.`shelters_shelter` (`id_shelter`, `name`, `description`, `email`, `web_site`, `workgroup_key`, `reminder_status`, `bed_capacity`, `phone_number`, `address`, `location_lat`, `location_lon`) VALUES ('3', 'Salvation Army - Booth House Shelter', 'The Booth House Shelter is a 24-hour emergency and transitional housing facility in Baltimore City for women, men, and families with children. Consisting of a 57-bed, emergency (30-90 days) shelter and a 19-bed', 'jacob.green@gmail.com', 'http://salvationarmycm.org/help/shelter/', 'SalvationArmyBoothHouseShelter', '1', '10', '410-685-8878', '1114 North Calvert Street, Baltimore, MD, 21202', '39.303187', '-76.613485');
INSERT INTO `shelters`.`shelters_shelter` (`id_shelter`, `name`, `description`, `email`, `workgroup_key`, `reminder_status`, `bed_capacity`, `phone_number`, `address`, `location_lat`, `location_lon`) VALUES ('4', 'Prisoner\'s Aid Association of Maryland', 'For homeless ex-offenders. Emergency and transitional shelter. Meals, Counseling. Employment program', 'jacob.green@gmail.com', 'PrisonersAidAssociationOfMaryland', '1', '10', '410-662-0353', '204 E. 25th Street, Balimore, MD 21218', '39.318376', '-76.613958');
INSERT INTO `shelters`.`shelters_shelter` (`id_shelter`, `name`, `description`, `email`, `web_site`, `workgroup_key`, `reminder_status`, `bed_capacity`, `phone_number`, `address`, `location_lat`, `location_lon`) VALUES ('5', 'Manna House', 'The Drop-In-Center provides services beginning with the morning meal from 8:00 to 10:15 a.m. daily and continues from 11:30 a.m. until 4 p.m (Monday through Friday). We serve an average of 176 men, women and children everyday. The meal we serve may be eggs, potatoes, oatmeal, fruit and coffee, or it', 'jacob.green@gmail.com', 'http://mannahouseinc.org/', 'MannaHouse', '1', '10', '410-889-3001', '435 E. 25th Street, Baltimore, MD 21218', '39.318104', '-76.610074');